apiVersion: v1
kind: Namespace
metadata:
  name: healthcare-platform
  labels:
    app.kubernetes.io/part-of: healthcare-asset-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: healthcare-platform-monitoring
  labels:
    app.kubernetes.io/part-of: healthcare-asset-platform
    environment: production
